version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "M@sterk3y"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: trickfx/meuscontatos:latest
    depends_on:
      - sqlserver
      - zabbix-server
    environment:
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=contatos;User Id=sa;Password=M@sterk3y;"
      ASPNETCORE_URLS: "http://host.docker.internal:8080"
      ZBX_SERVER_HOST: "zabbix-server"

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_JAVAGATEWAY_ENABLE: 'false'
    ports:
      - "10051:10051"
    depends_on:
      - zabbix-postgres

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    ports:
      - "8081:8080"
    depends_on:
      - zabbix-server
    links:
      - zabbix-server

  zabbix-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    volumes:
      - zabbix-postgres-data:/var/lib/postgresql/data

volumes:
  sqlserverdata:
  zabbix-postgres-data:
