version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "M@sterk3y"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: trickfx/meuscontatos:latest
    depends_on:
      - sqlserver
      - prometheus
    environment:
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=contatos;User Id=sa;Password=M@sterk3y;"
      ASPNETCORE_URLS: "http://host.docker.internal:8080"
      ASPNETCORE_ENVIRONMENT: "Production"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  sqlserverdata:
