{
 "title": "Meus Contatos Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Consumo de CPU %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumo de Memória Ram (em MB)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latência EndPoint /Home",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_duration_home_sum[1m]) / rate(request_duration_home_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência EndPoint /AdicionarContato",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(request_duration_add_sum[1m]) / rate(request_duration_add_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência EndPoint /EditarContato",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "rate(request_duration_alterar_sum[1m]) / rate(request_duration_alterar_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência EndPoint /ExcluirContato",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(request_duration_excluir_sum[1m]) / rate(request_duration_excluir_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Visualizações da Lista de Contatos",
   "type": "stat",
   "description": "Numero de acessos a lista de contatos",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "home_exibicoes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latência EndPoint /BuscaComFiltro",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "rate(request_duration_busca_filtro_sum[1m]) / rate(request_duration_busca_filtro_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contatos Adicionados",
   "type": "stat",
   "description": "Numero de contatos Adicionados",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contatos_adicionados", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Contatos Alterados",
   "type": "stat",
   "description": "Numero de contatos Alterados",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contatos_alterados", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Buscas com filtro",
   "type": "stat",
   "description": "Numero de buscas com filtro",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "buscas_filtro", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Contatos Excluidos",
   "type": "stat",
   "description": "Numero de contatos Excluidos",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "contatos_excluidos", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Erros ao adicionar contato",
   "type": "stat",
   "description": "Erros ao adicionar contato",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "erros_adicionar_contato", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Erros ao alterar contato",
   "type": "stat",
   "description": "Erros ao adicionar contato",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "erros_alterar_contato", "legendFormat": "__auto" }
   ]
  }
 ]
}