// <auto-generated />
using System;
using Infrastructure.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entity.Contato", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contato", (string)null);
                });

            modelBuilder.Entity("Core.Entity.DDD", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoDDD")
                        .HasColumnType("INT");

                    b.Property<int>("EstadoId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("DDD", (string)null);
                });

            modelBuilder.Entity("Core.Entity.Estado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("RegiaoId")
                        .HasColumnType("INT");

                    b.Property<int?>("RegiaoId1")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("RegiaoId1")
                        .IsUnique()
                        .HasFilter("[RegiaoId1] IS NOT NULL");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("Core.Entity.Regiao", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.HasKey("Id");

                    b.ToTable("Regiao", (string)null);
                });

            modelBuilder.Entity("Core.Entity.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContatoId")
                        .HasColumnType("INT");

                    b.Property<int>("DDD")
                        .HasColumnType("INT");

                    b.Property<int>("DddId")
                        .HasColumnType("INT");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.HasIndex("DddId");

                    b.ToTable("Telefone", (string)null);
                });

            modelBuilder.Entity("Core.Entity.DDD", b =>
                {
                    b.HasOne("Core.Entity.Estado", "Estado")
                        .WithMany("DDDs")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Core.Entity.Estado", b =>
                {
                    b.HasOne("Core.Entity.Regiao", "Regiao")
                        .WithMany("Estados")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entity.Regiao", null)
                        .WithOne("Estado")
                        .HasForeignKey("Core.Entity.Estado", "RegiaoId1");

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("Core.Entity.Telefone", b =>
                {
                    b.HasOne("Core.Entity.Contato", "Contato")
                        .WithMany("Telefones")
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entity.DDD", "Ddd")
                        .WithMany("Telefones")
                        .HasForeignKey("DddId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contato");

                    b.Navigation("Ddd");
                });

            modelBuilder.Entity("Core.Entity.Contato", b =>
                {
                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("Core.Entity.DDD", b =>
                {
                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("Core.Entity.Estado", b =>
                {
                    b.Navigation("DDDs");
                });

            modelBuilder.Entity("Core.Entity.Regiao", b =>
                {
                    b.Navigation("Estado")
                        .IsRequired();

                    b.Navigation("Estados");
                });
#pragma warning restore 612, 618
        }
    }
}
