USE CONTATOS

INSERT INTO REGIAO (NOME) VALUES('Nordeste')
INSERT INTO REGIAO (NOME) VALUES('Norte')
INSERT INTO REGIAO (NOME) VALUES('Centro Oeste')
INSERT INTO REGIAO (NOME) VALUES('Sudeste')
INSERT INTO REGIAO (NOME) VALUES('Sul')