USE CONTATOS

--LEVANTANDO IDs das regiões
DECLARE @NORDESTE INT
SELECT TOP 1 @NORDESTE = Id FROM REGIAO WHERE NOME = 'Nordeste'

DECLARE @NORTE INT
SELECT TOP 1 @NORTE = Id FROM REGIAO WHERE NOME = 'Norte'

DECLARE @CENTROOESTE INT
SELECT TOP 1 @CENTROOESTE = Id FROM REGIAO WHERE NOME = 'Centro Oeste'

DECLARE @SUDESTE INT
SELECT TOP 1 @SUDESTE = Id FROM REGIAO WHERE NOME = 'Sudeste'

DECLARE @SUL INT
SELECT TOP 1 @SUL = Id FROM REGIAO WHERE NOME = 'Sudeste'


--INSERT DOS ESTADOS POR REGIÃO

--NORTE
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Acre',@NORTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Amapá',@NORTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Amazonas',@NORTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Pará',@NORTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Rondônia',@NORTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Roraima',@NORTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Tocantins',@NORTE)


--NORDESTE
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Alagoas',@NORDESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Bahia',@NORDESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Ceará',@NORDESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Maranhão',@NORDESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Paraíba',@NORDESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Pernambuco',@NORDESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Piauí',@NORDESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Rio Grande do Norte',@NORDESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Sergipe',@NORDESTE)

--CENTRO OESTE
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Distrito Federal',@CENTROOESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Goiás',@CENTROOESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Mato Grosso',@CENTROOESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Mato Grosso do Sul',@CENTROOESTE)

--SUDESTE
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Espírito Santo',@SUDESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Minas Gerais',@SUDESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Rio de Janeiro',@SUDESTE)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('São Paulo',@SUDESTE)

--SUL
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Paraná',@SUL)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Rio Grande do Sul',@SUL)
INSERT INTO ESTADO (NOME,RegiaoId) VALUES('Santa Catarina',@SUL)

SELECT * FROM ESTADO